framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    stream: messenger
                    group: symfony
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    stream: messenger_failed
                    group: symfony
            sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
