
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
# Mercure est géré dans docker-compose.yml (instance partagée port 3010)
###< symfony/mercure-bundle ###
