services:

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: mitoera-api-database-1
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - place-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: place-redis
    ports:
      - "6379:6379"
    networks:
      - place-network

  mercure:
    image: dunglas/mercure
    container_name: place-mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3010'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_JWT_SECRET}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_JWT_SECRET}'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:5173 https://localhost:5173 http://localhost:5174 https://localhost:5174 http://localhost:8000 https://localhost:8000 http://localhost:3001 https://localhost:3001 http://localhost:3000 https://localhost:3000 http://127.0.0.1:5173 https://127.0.0.1:5173 http://127.0.0.1:5174 https://127.0.0.1:5174 http://127.0.0.1:8000 https://127.0.0.1:8000 http://127.0.0.1:3001 https://127.0.0.1:3001 http://127.0.0.1:3000 https://127.0.0.1:3000
        anonymous
        subscriptions
        ui
    ports:
      - "3010:3010"
    networks:
      - place-network

volumes:
  database_data:

networks:
  place-network:
    driver: bridge
